apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiro-api
  labels:
    app: kiro-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kiro-api
  template:
    metadata:
      labels:
        app: kiro-api
        tier: backend
    spec:
      containers:
        - name: kiro-api
          image: kiro-erp/app:latest
          ports:
            - containerPort: 4000
              name: http
          env:
            - name: NODE_ENV
              value: 'production'
            - name: PORT
              value: '4000'
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: kiro-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: kiro-secrets
                  key: redis-url
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kiro-secrets
                  key: jwt-secret
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1000m'
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: kiro-api-service
  labels:
    app: kiro-api
spec:
  selector:
    app: kiro-api
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  type: ClusterIP

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kiro-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kiro-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Pods
      pods:
        metric:
          name: http_requests_per_second
        target:
          type: AverageValue
          averageValue: '100'
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kiro-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kiro-api
