apiVersion: v1
kind: Namespace
metadata:
  name: kiro-erp
  labels:
    name: kiro-erp
    environment: production
    app: kiro-erp
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kiro-erp-quota
  namespace: kiro-erp
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kiro-erp-limits
  namespace: kiro-erp
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim