import { useColorScheme } from 'react-native';
import {
  MD3DarkTheme,
  MD3LightTheme,
  configureFonts,
} from 'react-native-paper';

const fontConfig = {
  labelLarge: {
    fontFamily: 'System',
    fontWeight: '500' as const,
    letterSpacing: 0.1,
    lineHeight: 20,
    fontSize: 14,
  },
  labelMedium: {
    fontFamily: 'System',
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 16,
    fontSize: 12,
  },
  labelSmall: {
    fontFamily: 'System',
    fontWeight: '500' as const,
    letterSpacing: 0.5,
    lineHeight: 14,
    fontSize: 11,
  },
  bodyLarge: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0.15,
    lineHeight: 24,
    fontSize: 16,
  },
  bodyMedium: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0.25,
    lineHeight: 20,
    fontSize: 14,
  },
  bodySmall: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0.4,
    lineHeight: 16,
    fontSize: 12,
  },
  titleLarge: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 28,
    fontSize: 22,
  },
  titleMedium: {
    fontFamily: 'System',
    fontWeight: '500',
    letterSpacing: 0.15,
    lineHeight: 24,
    fontSize: 16,
  },
  titleSmall: {
    fontFamily: 'System',
    fontWeight: '500',
    letterSpacing: 0.1,
    lineHeight: 20,
    fontSize: 14,
  },
  displayLarge: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: -0.25,
    lineHeight: 64,
    fontSize: 57,
  },
  displayMedium: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 52,
    fontSize: 45,
  },
  displaySmall: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 44,
    fontSize: 36,
  },
  headlineLarge: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 40,
    fontSize: 32,
  },
  headlineMedium: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 36,
    fontSize: 28,
  },
  headlineSmall: {
    fontFamily: 'System',
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 32,
    fontSize: 24,
  },
};

const lightTheme = {
  ...MD3LightTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3LightTheme.colors,
    primary: '#1976D2',
    primaryContainer: '#E3F2FD',
    secondary: '#FF9800',
    secondaryContainer: '#FFF3E0',
    tertiary: '#4CAF50',
    tertiaryContainer: '#E8F5E8',
    surface: '#FFFFFF',
    surfaceVariant: '#F5F5F5',
    background: '#FAFAFA',
    error: '#F44336',
    errorContainer: '#FFEBEE',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#0D47A1',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#E65100',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#1B5E20',
    onSurface: '#212121',
    onSurfaceVariant: '#757575',
    onBackground: '#212121',
    onError: '#FFFFFF',
    onErrorContainer: '#B71C1C',
    outline: '#E0E0E0',
    outlineVariant: '#F5F5F5',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#303030',
    inverseOnSurface: '#F5F5F5',
    inversePrimary: '#90CAF9',
    elevation: {
      level0: 'transparent',
      level1: '#F8F9FA',
      level2: '#F1F3F4',
      level3: '#E8EAED',
      level4: '#E3E5E8',
      level5: '#DADCE0',
    },
  },
};

const darkTheme = {
  ...MD3DarkTheme,
  fonts: configureFonts({ config: fontConfig }),
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#90CAF9',
    primaryContainer: '#0D47A1',
    secondary: '#FFB74D',
    secondaryContainer: '#E65100',
    tertiary: '#81C784',
    tertiaryContainer: '#1B5E20',
    surface: '#121212',
    surfaceVariant: '#1E1E1E',
    background: '#000000',
    error: '#EF5350',
    errorContainer: '#B71C1C',
    onPrimary: '#0D47A1',
    onPrimaryContainer: '#E3F2FD',
    onSecondary: '#E65100',
    onSecondaryContainer: '#FFF3E0',
    onTertiary: '#1B5E20',
    onTertiaryContainer: '#E8F5E8',
    onSurface: '#FFFFFF',
    onSurfaceVariant: '#BDBDBD',
    onBackground: '#FFFFFF',
    onError: '#B71C1C',
    onErrorContainer: '#FFEBEE',
    outline: '#424242',
    outlineVariant: '#2E2E2E',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#F5F5F5',
    inverseOnSurface: '#303030',
    inversePrimary: '#1976D2',
    elevation: {
      level0: 'transparent',
      level1: '#1E1E1E',
      level2: '#232323',
      level3: '#252525',
      level4: '#272727',
      level5: '#2C2C2C',
    },
  },
};

export const useAppTheme = () => {
  const colorScheme = useColorScheme();
  return colorScheme === 'dark' ? darkTheme : lightTheme;
};

export const theme = lightTheme;
