apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres-primary:5432
    database: kiro_erp
    user: kiro_readonly
    secureJsonData:
      password: kiro_readonly_password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: kiro_timeseries
    user: kiro_readonly
    secureJsonData:
      password: kiro_readonly_password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      timescaledb: true